# -*- coding: utf-8 -*-
"""Pregunta 18 exm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_KZK-6uccil3dzzSu09al5CDknwSHWc
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.stats.diagnostic import acorr_ljungbox
import warnings
warnings.filterwarnings("ignore")

# Step 1: Load the data from the Excel file
# File 'dpi_data.xlsx' is in the Colab environment
data = pd.read_excel('dpi_data.xlsx', header=0)
time_series = pd.Series(np.log(data['MONEY']))
series_name = "Log M1 Money Supply"

# Step 2: Plot the time series to visualize its behavior
plt.figure(figsize=(10, 6))
plt.plot(time_series, label=series_name)
plt.title('Time Series of Log M1 Money Supply (1951-1999)')
plt.xlabel('Time')
plt.ylabel('Log MONEY')
plt.legend()
plt.grid(True)
plt.savefig('log_money_time_series.png')
plt.show()

# Step 3: Unit Root Tests (ADF and KPSS) with Interpretation
def unit_root_tests(series, name):
    print(f"\nUnit Root Tests for {name}:")

    # ADF Test
    adf_result = adfuller(series)
    print("ADF Test:")
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
        print(f"    Implication: {name} does not have a unit root; suitable for ARMA modeling.")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")
        print(f"    Implication: {name} may have a unit root; consider differencing for ARIMA.")

    # KPSS Test
    kpss_result = kpss(series, regression='c')
    print("\nKPSS Test:")
    print(f'KPSS Statistic: {kpss_result[0]:.4f}')
    print(f'p-value: {kpss_result[1]:.4f}')
    print(f'Critical Values: {kpss_result[3]}')
    print("Interpretation:")
    if kpss_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is non-stationary")
        print(f"    Implication: {name} may require differencing to achieve stationarity.")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be stationary")
        print(f"    Implication: {name} is suitable for modeling without differencing.")

    # Combined Interpretation
    print("\nCombined Interpretation:")
    if adf_result[1] < 0.05 and kpss_result[1] >= 0.05:
        print(f"  - Both tests agree: {name} is stationary. Suitable for ARMA modeling.")
        return True
    elif adf_result[1] >= 0.05 and kpss_result[1] < 0.05:
        print(f"  - Both tests agree: {name} is non-stationary. Proceed with differencing for ARIMA.")
        return False
    else:
        print(f"  - Tests disagree: Mixed evidence on stationarity for {name}. Proceed with caution.")
        return False

# Run unit root tests
is_stationary = unit_root_tests(time_series, series_name)

# Step 4: Correlogram (ACF and PACF Plots) with Interpretation
# Adjust lags to be less than 50% of sample size (32 observations, so max lags < 16)
lags = 15
plt.figure(figsize=(12, 6))
plt.subplot(121)
plot_acf(time_series.dropna(), lags=lags, ax=plt.gca(), title='ACF of Original Series')
plt.subplot(122)
plot_pacf(time_series.dropna(), lags=lags, ax=plt.gca(), title='PACF of Original Series')
plt.tight_layout()
plt.savefig('correlogram_original.png')
plt.show()
print("\nCorrelogram Interpretation:")
print("  - ACF: Look for significant lags to determine the MA order (q).")
print("  - PACF: Look for significant lags to determine the AR order (p).")
print("  - If the series is non-stationary, examine the correlogram after differencing.")

# Step 5: Apply differencing if the series is not stationary
d = 0
diff_series = time_series.copy()
if not is_stationary:
    while True:
        adf_result = adfuller(diff_series.dropna())
        if adf_result[1] < 0.05:
            print(f'Series is stationary after {d} differencings')
            break
        if d >= 2:
            print('Reached maximum differencing order of 2. Proceeding with d=2.')
            break
        diff_series = diff_series.diff().dropna()
        d += 1
        unit_root_tests(diff_series, f'Differenced Series (d={d})')

    # Plot differenced series
    plt.figure(figsize=(10, 6))
    plt.plot(diff_series, label=f'{d}-times Differenced Series')
    plt.title(f'{d}-times Differenced Log M1 Money Supply')
    plt.xlabel('Time')
    plt.ylabel('Differenced Log MONEY')
    plt.legend()
    plt.grid(True)
    plt.savefig('differenced_series.png')
    plt.show()

    # Correlogram for differenced series
    diff_lags = min(lags, len(diff_series) // 2 - 1)
    plt.figure(figsize=(12, 6))
    plt.subplot(121)
    plot_acf(diff_series.dropna(), lags=diff_lags, ax=plt.gca(), title=f'ACF of Differenced Series (d={d})')
    plt.subplot(122)
    plot_pacf(diff_series.dropna(), lags=diff_lags, ax=plt.gca(), title=f'PACF of Differenced Series (d={d})')
    plt.tight_layout()
    plt.savefig('correlogram_differenced.png')
    plt.show()
    print("\nCorrelogram Interpretation (Differenced Series):")
    print("  - ACF: Significant lags suggest the MA order (q).")
    print("  - PACF: Significant lags suggest the AR order (p).")

# Step 6: Test for Random Walk (ARIMA(0,1,0))
print("\nTesting for Random Walk (ARIMA(0,1,0)):")
rw_model = ARIMA(time_series, order=(0, 1, 0))
rw_fit = rw_model.fit()
print(rw_fit.summary())
rw_residuals = rw_fit.resid
rw_lb_test = acorr_ljungbox(rw_residuals, lags=[10], return_df=True)
print("Ljung-Box Test for Random Walk Residuals:")
print(rw_lb_test)
print("Interpretation:")
if rw_lb_test['lb_pvalue'].iloc[0] > 0.05:
    print("  - p-value > 0.05: Residuals are white noise; series may follow a random walk.")
else:
    print("  - p-value <= 0.05: Residuals show autocorrelation; series is not a pure random walk.")

# Plot Random Walk fitted values
rw_fitted = time_series.iloc[0] + rw_residuals.cumsum()
historical_index = pd.RangeIndex(start=0, stop=len(time_series))
plt.figure(figsize=(10, 6))
plt.plot(historical_index, time_series, label='Observed Log M1 Money Supply', color='blue')
plt.plot(historical_index, rw_fitted, label='Random Walk Fitted Values', color='orange', linestyle='--')
plt.title('Random Walk Model Fit')
plt.xlabel('Time')
plt.ylabel('Log MONEY')
plt.legend()
plt.grid(True)
plt.savefig('random_walk_fit.png')
plt.show()

# Step 7: Fit ARMA Model (if stationary) or ARIMA Model
def find_best_arma_arima(series, name, max_p=3, max_d=2, max_q=3, use_d=0):
    best_aic = float('inf')
    best_order = None
    for p in range(max_p + 1):
        for d in range(max_d + 1) if use_d == -1 else [use_d]:
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except:
                    continue
    print(f"\nBest Model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    return best_order

if is_stationary:
    print("\nFitting ARMA Model (since series is stationary):")
    order = find_best_arma_arima(time_series, series_name, use_d=0)
else:
    print("\nFitting ARIMA Model (since series is non-stationary):")
    order = find_best_arma_arima(time_series, series_name, use_d=-1)

# Fit the final model
model = ARIMA(time_series, order=order)
model_fit = model.fit()
print(model_fit.summary())

# Plot ARMA/ARIMA fitted values
fitted_values = model_fit.fittedvalues
plt.figure(figsize=(10, 6))
plt.plot(historical_index, time_series, label='Observed Log M1 Money Supply', color='blue')
plt.plot(historical_index, fitted_values, label=f'{"ARMA" if order[1]==0 else "ARIMA"} Fitted Values', color='green', linestyle='--')
plt.title(f'{"ARMA" if order[1]==0 else "ARIMA"} Model Fit')
plt.xlabel('Time')
plt.ylabel('Log MONEY')
plt.legend()
plt.grid(True)
plt.savefig(f'{"arma" if order[1]==0 else "arima"}_fit.png')
plt.show()

# Step 8: Residual Analysis
residuals = model_fit.resid
plt.figure(figsize=(10, 6))
plt.plot(historical_index, residuals, label='Residuals')
plt.title('Residuals of ARIMA/ARMA Model')
plt.xlabel('Time')
plt.ylabel('Residuals')
plt.legend()
plt.grid(True)
plt.savefig('residuals.png')
plt.show()

# Correlogram of residuals
residual_lags = min(15, len(residuals) // 2 - 1)
plt.figure(figsize=(10, 6))
plot_acf(residuals, lags=residual_lags, ax=plt.gca(), title='ACF of Residuals')
plt.savefig('acf_residuals.png')
plt.show()

# Ljung-Box test
lb_test = acorr_ljungbox(residuals, lags=[10], return_df=True)
print("\nLjung-Box Test for Residual Autocorrelation:")
print(lb_test)
print("Interpretation:")
if lb_test['lb_pvalue'].iloc[0] > 0.05:
    print("  - p-value > 0.05: Residuals are white noise; model captures the series well.")
else:
    print("  - p-value <= 0.05: Residuals show autocorrelation; consider a different model specification.")

# Step 9: Cointegration Test (Not Applicable with One Series)
print("\nCointegration Test:")
print("  - Note: Cointegration requires at least two time series to test for a long-run relationship.")
print("  - Since we only have one series (Log M1 Money Supply), cointegration testing is not applicable.")
print("  - Implication: Proceed with univariate modeling (ARIMA/ARMA).")

# Step 10: Forecast with Detailed Graphic
forecast_steps = 12
forecast_obj = model_fit.get_forecast(steps=forecast_steps)
forecast = forecast_obj.predicted_mean
conf_int = forecast_obj.conf_int()

# Get fitted values
fitted_values = model_fit.fittedvalues
historical_index = pd.RangeIndex(start=0, stop=len(time_series))
forecast_index = pd.RangeIndex(start=len(time_series), stop=len(time_series) + forecast_steps)

# Plot observed data, fitted values, forecast, and confidence intervals
plt.figure(figsize=(12, 6))
plt.plot(historical_index, time_series, label='Observed Log M1 Money Supply', color='blue')
plt.plot(historical_index, fitted_values, label=f'{"ARMA" if order[1]==0 else "ARIMA"} Fitted Values', color='green', linestyle='--')
plt.plot(forecast_index, forecast, label='Forecast', color='red')
plt.fill_between(forecast_index,
                 conf_int.iloc[:, 0],
                 conf_int.iloc[:, 1],
                 color='pink',
                 alpha=0.3,
                 label='95% Confidence Interval')
plt.title(f'{"ARMA" if order[1]==0 else "ARIMA"} Model: Log M1 Money Supply with Forecast')
plt.xlabel('Time')
plt.ylabel('Log MONEY')
plt.legend()
plt.grid(True)
plt.savefig(f'{"arma" if order[1]==0 else "arima"}_forecast.png')
plt.show()

# Forecast Interpretation
last_value = time_series.iloc[-1]
mean_forecast = forecast.mean()
print("\nForecast Interpretation:")
print(f"Last observed value: {last_value:.4f}")
print(f"Average forecast value: {mean_forecast:.4f}")
print(f"Forecast change: {mean_forecast - last_value:.4f}")
if mean_forecast > last_value:
    print("Trend: Upward forecast trend")
elif mean_forecast < last_value:
    print("Trend: Downward forecast trend")
else:
    print("Trend: Flat forecast trend")
print(f"95% CI range at period {forecast_steps}: [{conf_int.iloc[-1, 0]:.4f}, {conf_int.iloc[-1, 1]:.4f}]")

# Print forecast values
print('\nForecasted Values:')
for i, val in enumerate(forecast, start=1):
    print(f'Period {len(time_series) + i}: {val:.4f}')